DROP TABLE IF EXISTS author;

CREATE TABLE author (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	alias VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS organism;
CREATE TABLE organism (
	dna VARCHAR(255) NOT NULL,
	PRIMARY KEY (dna)
);